log_verbose: true
enable_rag: false
mode: auto
KB_ROOT_PATH: /home/hellower/VulnBot/data/knowledge_base
http_default_timeout: 3000
kali:
  hostname: localhost
  port: 22
  username: root
  password: kali
default_bind_host: 0.0.0.0
api_server:
  host: 0.0.0.0
  port: 7861
  public_host: 127.0.0.1
  public_port: 7861
webui_server:
  host: 0.0.0.0
  port: 8501
