default_vs_type: milvus
milvus:
  uri: http://localhost:19530
  user: root
  password: Milvus
kb_name: invitroMC
chunk_size: 750
overlap_size: 150
top_n: 1
top_k: 3
score_threshold: 0.5
search_params:
  metric_type: L2
  params:
    nprobe: 10
index_params:
  metric_type: L2
  index_type: HNSW
  params:
    M: 16
    efConstruction: 200
text_splitter_dict:
  SpacyTextSplitter:
    source: huggingface
    tokenizer_name_or_path: gpt2
  RecursiveCharacterTextSplitter:
    source: tiktoken
    tokenizer_name_or_path: cl100k_base
text_splitter_name: RecursiveCharacterTextSplitter
